# Generated by Django 5.0.6 on 2025-03-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('book_time', models.TimeField()),
                ('curr_date', models.DateTimeField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.doctor')),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient')),
            ],
        ),
    ]
