# Generated by Django 5.0.6 on 2025-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='curr_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
