# Generated by Django 5.0.6 on 2025-03-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0003_alter_appointment_curr_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='con_fee',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
