# Generated by Django 5.0.6 on 2025-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0004_doctor_con_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('amt', models.IntegerField(max_length=100)),
            ],
        ),
    ]
