# Generated by Django 5.0.6 on 2025-03-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='app_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.appointment'),
            preserve_default=False,
        ),
    ]
