# Generated by Django 5.0.6 on 2025-03-26 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0006_payment_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='app_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.appointment'),
        ),
    ]
