# Generated by Django 5.0.6 on 2025-03-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0007_alter_payment_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
