# Generated by Django 5.0.6 on 2025-03-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0008_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
