# Generated by Django 5.0.6 on 2025-03-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0009_appointment_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pres',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
