# Generated by Django 5.0.6 on 2025-03-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0010_appointment_pres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
