# Generated by Django 5.0.6 on 2025-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0011_alter_appointment_pres'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
