# Generated by Django 5.0.6 on 2025-04-03 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0012_appointment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=100)),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
            ],
        ),
    ]
