# Generated by Django 5.0.6 on 2025-04-03 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0013_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='loginid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login'),
            preserve_default=False,
        ),
    ]
