# Generated by Django 5.0.6 on 2025-04-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0014_lab_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_date', models.DateTimeField(auto_now_add=True)),
                ('test_details', models.CharField(max_length=100)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.doctor')),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient')),
            ],
        ),
    ]
