# Generated by Django 5.0.6 on 2025-04-08 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0015_labtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='hosp_id',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='pat_id',
        ),
        migrations.AddField(
            model_name='labtest',
            name='app_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.appointment'),
            preserve_default=False,
        ),
    ]
