# Generated by Django 5.0.6 on 2025-04-08 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0016_remove_labtest_doc_id_remove_labtest_hosp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='lab_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.lab'),
            preserve_default=False,
        ),
    ]
