# Generated by Django 5.0.6 on 2025-04-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0017_labtest_lab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
