# Generated by Django 5.0.6 on 2025-04-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0018_lab_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
