# Generated by Django 5.0.6 on 2025-04-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0019_labtest_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='test_detail_add',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
