# Generated by Django 5.0.6 on 2025-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0020_labtest_test_detail_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='test_detail_add',
        ),
        migrations.AddField(
            model_name='labtest',
            name='report_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
