# Generated by Django 5.0.6 on 2025-04-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0021_remove_labtest_test_detail_add_labtest_report_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='report_text',
            new_name='report_given',
        ),
    ]
