# Generated by Django 5.0.6 on 2025-04-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0023_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='loginid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login'),
            preserve_default=False,
        ),
    ]
