# Generated by Django 5.0.6 on 2025-04-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0024_insurance_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ins_taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('ins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.insurance')),
            ],
        ),
    ]
