# Generated by Django 5.0.6 on 2025-04-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0025_ins_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ins_taken',
            name='ins',
        ),
    ]
