# Generated by Django 5.0.6 on 2025-04-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0026_remove_ins_taken_ins'),
    ]

    operations = [
        migrations.AddField(
            model_name='ins_taken',
            name='type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
