# Generated by Django 5.0.6 on 2025-04-30 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0027_ins_taken_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ins_pat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('ins_num', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('curr_date', models.DateTimeField(auto_now_add=True)),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient')),
            ],
        ),
    ]
