# Generated by Django 5.0.6 on 2025-05-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0030_ins_pat_sa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
