# Generated by Django 5.0.6 on 2025-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0031_alter_appointment_status_alter_appointment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ins_pat',
            name='hospital_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ins_pat',
            name='insurance_amount',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
