# Generated by Django 5.0.6 on 2025-05-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0032_ins_pat_hospital_notes_ins_pat_insurance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ins_pat',
            name='hospital_notes',
        ),
        migrations.RemoveField(
            model_name='ins_pat',
            name='insurance_amount',
        ),
    ]
