# Generated by Django 5.0.6 on 2025-05-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0033_remove_ins_pat_hospital_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ins_pat',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
