# Generated by Django 5.0.6 on 2025-05-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0034_ins_pat_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ins_pat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hospital_notes/'),
        ),
    ]
