# Generated by Django 5.0.6 on 2025-05-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0036_ins_pat_amt_ins_pat_ins_amt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pr_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
