# Generated by Django 5.0.6 on 2025-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0037_patient_pr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='before_or_after_food',
            field=models.CharField(blank=True, choices=[('Before', 'Before Food'), ('After', 'After Food')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Night', 'Night')], max_length=20, null=True),
        ),
    ]
