# Generated by Django 5.0.6 on 2025-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0039_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='before_or_after_food',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_of_day',
            field=models.TextField(blank=True, null=True),
        ),
    ]
