# Generated by Django 5.0.6 on 2025-05-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0040_alter_appointment_before_or_after_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='medicines',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
