# Generated by Django 5.0.6 on 2025-05-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0041_remove_appointment_medicine_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='before_or_after_food',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_of_day',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=50)),
                ('before_or_after_food', models.CharField(choices=[('Before', 'Before Food'), ('After', 'After Food')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hosp_app.appointment')),
            ],
        ),
    ]
