# Generated by Django 5.0.6 on 2025-06-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0045_recipient_organmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
