# Generated by Django 5.0.6 on 2025-06-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0046_labtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='card_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='exp_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
