# Generated by Django 5.0.6 on 2025-06-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0047_labtest_card_name_labtest_card_number_labtest_cvv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='test_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_details',
            field=models.TextField(),
        ),
    ]
