# Generated by Django 5.0.6 on 2025-06-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0048_labtest_test_prices_alter_labtest_test_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
