# Generated by Django 5.0.6 on 2025-06-14 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosp_app', '0050_remove_appointment_doc_id_remove_appointment_hosp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone_number', models.CharField(max_length=15)),
                ('organ_name', models.CharField(max_length=100)),
                ('acknowledgment', models.FileField(upload_to='acknowledgments/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ins_taken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('organ_needed', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('specification', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('qualif', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('con_fee', models.CharField(max_length=100)),
                ('hosp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField()),
                ('book_time', models.TimeField()),
                ('cancel', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10, null=True)),
                ('pres', models.CharField(blank=True, max_length=100, null=True)),
                ('curr_date', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.doctor')),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Labtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_date', models.DateTimeField(auto_now_add=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('report_given', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('exp_date', models.CharField(blank=True, max_length=10, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('test_details', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('test_prices', models.JSONField(default=dict)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.appointment')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_id', models.CharField(max_length=100)),
                ('agent_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login')),
            ],
        ),
        migrations.AddField(
            model_name='hosp',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('pr_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Ins_pat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('doc_name', models.CharField(max_length=100)),
                ('ins_num', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('curr_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('sa', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='hospital_notes/')),
                ('amt', models.CharField(max_length=100)),
                ('ins_amt_status', models.IntegerField(default=0)),
                ('hosp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.hosp')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='pat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('amt', models.IntegerField(max_length=100)),
                ('app_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosp_app.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=50)),
                ('before_or_after_food', models.CharField(choices=[('Before', 'Before Food'), ('After', 'After Food')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hosp_app.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='OrganMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.donation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.recipient')),
            ],
        ),
    ]
