# Generated by Django 5.0.6 on 2025-06-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0051_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='inc_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
