# Generated by Django 5.0.6 on 2025-06-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0052_alter_insurance_inc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='inc_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
