# Generated by Django 5.0.6 on 2025-06-18 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0053_alter_insurance_inc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.doctor')),
                ('pat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp_app.patient')),
                ('transfer_doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_to', to='hosp_app.doctor')),
            ],
        ),
    ]
