# Generated by Django 5.0.6 on 2025-06-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp_app', '0054_transferappointment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transferappointment',
            unique_together={('pat_id', 'transfer_doc_id')},
        ),
    ]
