from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from.import views
urlpatterns = [

    
    path('',views.index,name='index'),
    path('login',views.login,name='login'),
    path('reg_hosp',views.reg_hosp,name='reg_hosp'),
    path('admin_mod',views.admin_mod,name='admin_mod'),
    path('doc_mod',views.doc_mod,name='doc_mod'),
    path('pat_mod',views.pat_mod,name='pat_mod'),
    path('hosp_mod',views.hosp_mod,name='hosp_mod'),
    path('reg_pat',views.reg_pat,name='reg_pat'),
    path('doc_reg',views.doc_reg,name='doc_reg'),
    path('lab_reg',views.lab_reg,name='lab_reg'),
    path('lab_mod',views.lab_mod,name='lab_mod'),
    path('hosp_reg_show',views.hosp_reg_show,name='hosp_reg_show'),
    path('doc_reg_show',views.doc_reg_show,name='doc_reg_show'),
    path('pat_reg_show',views.pat_reg_show,name='pat_reg_show'),
    path('approve/<int:id>',views.approve,name='approve'),
    path('reject/<int:id>',views.reject,name='reject'),
    path('doc_pro_edit',views.doc_pro_edit,name='doc_pro_edit'),
    path('hosp_pro_edit',views.hosp_pro_edit,name='hosp_pro_edit'),
    path('pat_pro_edit',views.pat_pro_edit,name='pat_pro_edit'),
    path('hosp_pat_show',views.hosp_pat_show,name='hosp_pat_show'),
    path('doc_pat_show/<int:id>',views.doc_pat_show,name='doc_pat_show'),
    path('pat_appointment_date/<int:id>/<int:hosp_id>',views.pat_appointment_date,name='pat_appointment_date'),
    path('pat_appointment_show',views.pat_appointment_show,name='pat_appointment_show'),
    path('pat_payment/<int:id>',views.pat_payment,name='pat_payment'),
    path('pat_appoint_show_admin',views.pat_appoint_show_admin,name='pat_appoint_show_admin'),
    path('doctor_pat_show',views.doctor_pat_show,name='doctor_pat_show'),
    path('cancel_appa/<int:id>',views.cancel_appa,name='cancel_appa'),
    path('presc_add/<int:id>',views.presc_add,name='presc_add'),
    path('pat_presc_show',views.pat_presc_show,name='pat_presc_show'),
    path('doc_presc_show',views.doc_presc_show,name='doc_presc_show'),
    path('edit_presc/<int:id>',views.edit_presc,name='edit_presc'),
    path('delete_presc/<int:id>',views.delete_presc,name='delete_presc'),
    path('web_con/<int:id>',views.web_con,name='web_con'),
    path('save_appointment_url/<int:id>/',views.save_appointment_url,name='save_appointment_url'),
    path('lab_test_doc/<int:id>/<int:lab_id>',views.lab_test_doc,name='lab_test_doc'),
    path('lab_doc_show/<int:id>',views.lab_doc_show,name='lab_doc_show'),
    path('lab_profile_edit',views.lab_profile_edit,name='lab_profile_edit'),
    path('lab_show_doc_request',views.lab_show_doc_request,name='lab_show_doc_request'),
    path("update_lab_status/<int:lab_test_id>/",views.update_lab_status, name="update_lab_status"),

    path('lab_file_upload/<int:id>',views.lab_file_upload,name='lab_file_upload'),
    path('lab_report_show_doc',views.lab_report_show_doc,name='lab_report_show_doc'),
    path('lab_report_show_pat',views.lab_report_show_pat,name='lab_report_show_pat'),
    path('generate-report/<int:labtest_id>/',views.generate_lab_report, name='generate_lab_report'),
    path('lab_edit_del',views.lab_edit_del, name='lab_edit_del'),
    path('edit_report/<int:id>',views.edit_report,name='edit_report'),
    path('delete_report/<int:id>',views.delete_report,name='delete_report'),
    path('reg_inc',views.reg_inc,name='reg_inc'),
    path('inc_mod',views.inc_mod,name='inc_mod'),
    path('inc_pro_edit',views.inc_pro_edit,name='inc_pro_edit'),
    path('ins_scheme',views.ins_scheme,name='ins_scheme'),
    path('ins_pat_show',views.ins_pat_show,name='ins_pat_show'),
    path('ins_pat_hosp_show/<int:id>',views.ins_pat_hosp_show,name='ins_pat_hosp_show'),
    path('ins_details_pat/<int:id>/<int:hosp_id>',views.ins_details_pat,name='ins_details_pat'),
    path('hosp_pat_ins_req',views.hosp_pat_ins_req,name='hosp_pat_ins_req'),
    path('verify_ins/<int:id>',views.verify_ins,name='verify_ins'),
    path('verified_list',views.verified_list,name='verified_list'),
    path("ins_accept/<int:id>/<str:action>/", views.ins_accept, name="ins_accept"),
    path("pat_ins_track/<int:id>", views.pat_ins_track, name="pat_ins_track"),
    path("pat_ins_req_show", views.pat_ins_req_show, name="pat_ins_req_show"),
    path("hosp_pat_ins_status", views.hosp_pat_ins_status, name="hosp_pat_ins_status"),
    path("hosp_pat_req_track/<int:id>", views.hosp_pat_req_track, name="hosp_pat_req_track"),
    path("claim_amt_tr/<int:id>", views.claim_amt_tr, name="claim_amt_tr"),
    path("all_pat_prnumber", views.all_pat_prnumber, name="all_pat_prnumber"),
    path("all_pat_prnumber_hosp", views.all_pat_prnumber_hosp, name="all_pat_prnumber_hosp"),
    path("hosp_pat_appointment", views.hosp_pat_appointment, name="hosp_pat_appointment"),
    path("hosp_docs_show", views.hosp_docs_show, name="hosp_docs_show"),
    path('generate_appointment_pdf/<int:appointment_id>', views.generate_appointment_pdf, name='generate_appointment_pdf'),
    path("ins_show_admin", views.ins_show_admin, name="ins_show_admin"),
    path("ins_pat_show_admin", views.ins_pat_show_admin, name="ins_pat_show_admin"),
    path("labs_show_admin", views.labs_show_admin, name="labs_show_admin"),
    path("logout", views.logout, name="logout"),
    path("complaint_view", views.complaint_view, name="complaint_view"),
    path("admin_complaint_list", views.admin_complaint_list, name="admin_complaint_list"),
    path("admin_reply/<int:id>", views.admin_reply, name="admin_reply"),
    path("patient_complaint_list", views.patient_complaint_list, name="patient_complaint_list"),
    path("donate_organ", views.donate_organ, name="donate_organ"),
    # path("matches", views.matches, name="matches"),
    path("recipient_form", views.recipient_form, name="recipient_form"),
    path('matches/<str:blood_group>/<str:organ_needed>/', views.matches, name='matches'),  # ✅ Accept values
    path('update_doctor_fee/<int:doctor_id>/', views.update_doctor_fee, name='update_doctor_fee'),
    path('patient_lab_tests', views.patient_lab_tests, name='patient_lab_tests'),
    path("update_lab_payment/<int:test_id>/", views.update_lab_payment, name="update_lab_payment"),

    path('xray/',views.xray,name='xray'),
    path('ask_health/', views.ask_health, name='ask_health'),
    path('ask/', views.ask, name='ask'),
    path("transfer_patient/<int:appointment_id>/", views.transfer_patient, name="transfer_patient"),
    path("transferred_patients/", views.transferred_patients, name="transferred_patients"),



]


